# Generated by Django 5.2.8 on 2026-01-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default='', max_length=100),
        ),
    ]
