# Generated by Django 5.2.8 on 2025-12-06 16:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='card_num',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='date_of_birth',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('ua', 'Украинский')], default='ru', max_length=100),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region='UA'),
        ),
    ]
