# Generated by Django 5.2.8 on 2026-03-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_baseuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='city',
            field=models.CharField(blank=True, choices=[('kyiv', 'Киев'), ('kharkiv', 'Харьков'), ('odesa', 'Одесса'), ('dnipro', 'Днепр'), ('lviv', 'Львов'), ('zaporizhzhia', 'Запорожье'), ('mykolaiv', 'Николаев'), ('poltava', 'Полтава'), ('chernihiv', 'Чернигов'), ('sumy', 'Сумы')], max_length=100),
        ),
    ]
