server {
    listen 80;
    server_name 35.184.44.159;  # твой публичный IP

    # Статика и медиа
    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    # Проксирование на Django
    location / {
        proxy_pass http://web:8000;  # web — имя сервиса в docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
