# Generated by Django 5.2.8 on 2026-02-17 17:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_rename_end_data_movie_end_date_and_more'),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='data',
            new_name='date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cms.movieformat'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('movie', 'hall', 'date', 'time', 'format')},
        ),
    ]
