# Generated by Django 5.2.8 on 2026-02-17 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_rename_end_data_movie_end_date_and_more'),
        ('main', '0003_alter_schedule_options_rename_data_schedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cms.movieformat'),
        ),
    ]
