# Generated by Django 5.2.8 on 2026-02-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_alter_movie_format_movie'),
        ('main', '0004_alter_schedule_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='format',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cms.movieformat'),
        ),
    ]
