# Generated by Django 5.2.8 on 2026-02-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_schedule_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
