# Generated by Django 5.2.8 on 2026-02-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_schedule_date_alter_schedule_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('booking', 'Бронь'), ('purchase', 'Покупка')], default='booking', max_length=10),
        ),
    ]
