# Generated by Django 5.2.7 on 2025-10-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='')),
                ('background', models.CharField(default='#FFFFFF', max_length=7)),
                ('is_use_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('key_words', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
                ('image_top_banner', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=255)),
                ('gallery', models.ManyToManyField(to='cms.gallery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=False)),
                ('creation_data', models.DateTimeField()),
                ('gallery', models.ManyToManyField(to='cms.gallery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
                ('url', models.URLField(max_length=255)),
                ('format_3d', models.BooleanField(default=False)),
                ('format_2d', models.BooleanField(default=False)),
                ('format_imax', models.BooleanField(default=False)),
                ('gallery', models.ManyToManyField(to='cms.gallery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('scheme_image', models.ImageField(upload_to='')),
                ('top_banner_image', models.ImageField(upload_to='')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.cinema')),
                ('gallery', models.ManyToManyField(to='cms.gallery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('speed', models.IntegerField()),
                ('slider', models.ManyToManyField(to='cms.slider')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('speed', models.IntegerField()),
                ('slider', models.ManyToManyField(to='cms.slider')),
            ],
        ),
    ]
