# Generated by Django 5.2.8 on 2025-12-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_data', models.DateTimeField()),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
                ('url', models.URLField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.CharField(choices=[('NEWS', 'Новости'), ('ACTION', 'Акции')], default='NEWS', max_length=10)),
                ('gallery', models.ManyToManyField(to='cms.gallery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock')),
            ],
        ),
    ]
