# Generated by Django 5.2.8 on 2025-12-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_cinema_seo_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
