# Generated by Django 5.2.8 on 2025-12-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cinema_conditions_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock'),
        ),
    ]
