# Generated by Django 5.2.8 on 2025-12-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_cinema_seo_block'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='seo_block',
        ),
        migrations.AddField(
            model_name='seoblock',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='cms.gallery'),
        ),
    ]
