# Generated by Django 5.2.8 on 2025-12-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_cinema_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='is_draft',
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
