# Generated by Django 5.2.8 on 2025-12-18 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_cinema_is_draft_alter_seoblock_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall',
            name='top_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
