# Generated by Django 5.2.8 on 2025-12-30 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_hall_date_create_alter_hall_top_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cinema'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='gallery',
            field=models.ManyToManyField(null=True, to='cms.gallery'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='scheme_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock'),
        ),
    ]
