# Generated by Django 5.2.8 on 2026-01-01 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_hall_is_default_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='cms.gallery'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock'),
        ),
    ]
