# Generated by Django 5.2.8 on 2026-01-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_updates_gallery_alter_updates_seo_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
