# Generated by Django 5.2.8 on 2026-01-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_cinema_description_en_cinema_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='number_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='number_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
