# Generated by Django 5.2.8 on 2026-01-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_hall_description_en_hall_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hall',
            name='number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='number_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
