# Generated by Django 5.2.8 on 2026-01-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_cinema_description_alter_cinema_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
