# Generated by Django 5.2.8 on 2026-01-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_updates_description_en_updates_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='updates',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
