# Generated by Django 5.2.8 on 2026-01-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_updates_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='publication_data',
            field=models.DateField(),
        ),
    ]
