# Generated by Django 5.2.8 on 2026-01-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_updates_publication_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebanner',
            name='speed',
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='type_banner',
            field=models.CharField(choices=[('TP', 'На главной вверх'), ('NB', 'На главной новости и акции')], default='TP', max_length=2),
        ),
        migrations.AddField(
            model_name='slider',
            name='speed',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='NewsPromoBanner',
        ),
    ]
