# Generated by Django 5.2.8 on 2026-01-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_remove_homepagebanner_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='speed',
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='speed',
            field=models.IntegerField(default=5),
        ),
    ]
