# Generated by Django 5.2.8 on 2026-01-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_remove_slider_speed_homepagebanner_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='is_use_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='speed',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='type_banner',
            field=models.CharField(choices=[('TB', 'На главной вверх'), ('NB', 'На главной новости и акции')], default='TB', max_length=2),
        ),
    ]
