# Generated by Django 5.2.8 on 2026-01-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_alter_backgroundbanner_is_use_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='is_use_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='backgroundbanner',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
