# Generated by Django 5.2.8 on 2026-01-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_backgroundbanner_is_use_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
