# Generated by Django 5.2.8 on 2026-02-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_movie_end_date_movie_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='format_2d',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='format_3d',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='format_imax',
        ),
        migrations.AddField(
            model_name='movie',
            name='format_movie',
            field=models.CharField(choices=[('3D', '3D'), ('2D', '2D'), ('imax', 'IMAX')], default='2D'),
        ),
    ]
