# Generated by Django 5.2.8 on 2026-02-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_remove_movie_format_2d_remove_movie_format_3d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format_movie',
            field=models.CharField(choices=[('3D', '3D'), ('2D', '2D'), ('IMAX', 'IMAX')], default='2D', max_length=10),
        ),
    ]
