# Generated by Django 5.2.8 on 2026-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_alter_movie_format_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='format_movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='format_movie',
            field=models.ManyToManyField(related_name='movies', to='cms.movieformat'),
        ),
    ]
