# Generated by Django 5.2.8 on 2026-02-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_movieformat_remove_movie_format_movie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='end_date',
            new_name='end_data',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='start_date',
            new_name='start_data',
        ),
    ]
