# Generated by Django 5.2.8 on 2026-02-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_rename_end_date_movie_end_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='start_data',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='hall',
            name='gallery',
            field=models.ManyToManyField(to='cms.gallery'),
        ),
    ]
