# Generated by Django 5.2.8 on 2026-02-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_rename_end_data_movie_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format_movie',
            field=models.ManyToManyField(default=1, related_name='movies', to='cms.movieformat'),
        ),
    ]
