# Generated by Django 5.2.8 on 2026-02-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_alter_movie_format_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format_movie',
            field=models.ManyToManyField(blank=True, related_name='movies', to='cms.movieformat'),
        ),
    ]
