# Generated by Django 5.2.8 on 2026-03-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_mailing_created_at_mailing_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mailings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='file',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='is_active',
        ),
        migrations.AddField(
            model_name='mailing',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailing',
            name='sent_emails',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('processing', 'В процессе'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='mailing',
            name='total_emails',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailing',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.mailtemplate'),
        ),
    ]
