# Generated by Django 5.2.8 on 2026-03-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_mailtemplate_remove_mailing_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtemplate',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
    ]
