# Generated by Django 5.2.8 on 2026-03-20 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_remove_mailtemplate_is_active_delete_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IZ', 'ИЖ'), ('JAVA', 'Ява'), ('URAL', 'Урал'), ('DNIPRO', 'Днепр'), ('PARTS', 'Запчасти')], default='IZ', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'Доллар'), ('UAH', 'Гривна')], default='UAH', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='contact',
            name='cinema',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='cms.cinema'),
        ),
    ]
