# Generated by Django 5.2.8 on 2026-03-21 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_product_remove_cinema_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='seo_block',
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Главная страница'), ('about_cinema', 'О кинотеатре'), ('cafe_bar', 'Кафе - Бар'), ('vip', 'Vip-зал'), ('ads', 'Реклама'), ('kids_room', 'Детская комната'), ('contacts', 'Контакты')], default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='creation_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='cms.gallery'),
        ),
        migrations.AlterField(
            model_name='page',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock'),
        ),
    ]
