# Generated by Django 5.2.8 on 2026-03-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_remove_contact_seo_block_page_page_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='tittle',
            new_name='title',
        ),
    ]
