# Generated by Django 5.2.8 on 2026-03-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_page_description_en_page_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cinema',
        ),
    ]
