# Generated by Django 5.2.8 on 2026-03-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_contact_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
