# Generated by Django 5.2.8 on 2026-03-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_alter_contact_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='tittle',
            new_name='title',
        ),
    ]
